/**
 * news-curator strategy — Crypto / Filecoin news digest.
 *
 * Data sources:
 *   - CryptoCompare public news API (no key required for basic access)
 *
 * Cadence: daily
 * Output:  Markdown digest
 * Category: research
 */

import type { ArtifactOutput } from "./market-analyst.js";

interface CCNewsItem {
  id: string;
  title: string;
  body: string;
  url: string;
  source: string;
  published_on: number;
  categories: string;
}

async function fetchFilecoinNews(): Promise<CCNewsItem[]> {
  const apiKey = process.env.CRYPTOCOMPARE_API_KEY ?? "";
  const url =
    `https://min-api.cryptocompare.com/data/v2/news/?categories=Filecoin,Storage,DePIN` +
    `&excludeCategories=Sponsored` +
    `&lang=EN` +
    `&feeds=coindesk,cointelegraph,decrypt` +
    (apiKey ? `&api_key=${apiKey}` : "");

  const res = await fetch(url, { signal: AbortSignal.timeout(10_000) });
  if (!res.ok) throw new Error(`CryptoCompare news fetch failed: ${res.status}`);
  const json = await res.json() as { Data?: CCNewsItem[]; Message?: string };
  return json.Data ?? [];
}

export async function run(): Promise<ArtifactOutput> {
  const timestamp = new Date().toISOString();
  const date = timestamp.slice(0, 10);

  let items: CCNewsItem[] = [];
  try {
    items = await fetchFilecoinNews();
  } catch (e) {
    console.warn("[news-curator] fetch failed, using empty digest:", e);
  }

  // Build markdown digest
  const top = items.slice(0, 10);
  const lines: string[] = [
    `# Filecoin / DePIN News Digest — ${date}`,
    ``,
    `> Generated by news-curator strategy agent at ${timestamp}`,
    `> Sources: CryptoCompare (coindesk, cointelegraph, decrypt)`,
    ``,
    `## Top Stories`,
    ``,
  ];

  if (top.length === 0) {
    lines.push("_No stories fetched this cycle. Check CryptoCompare API availability._");
  }

  for (const item of top) {
    const pubDate = new Date(item.published_on * 1000).toISOString().slice(0, 10);
    lines.push(`### ${item.title}`);
    lines.push(`**Source:** ${item.source} · ${pubDate}`);
    lines.push(``);
    lines.push(item.body.slice(0, 400) + (item.body.length > 400 ? "…" : ""));
    lines.push(`[Read more](${item.url})`);
    lines.push(``);
    lines.push(`---`);
    lines.push(``);
  }

  return {
    content: lines.join("\n"),
    mimeType: "text/markdown",
    listing: {
      priceUsdc: 0.05,
      license: "CC-BY-4.0",
      category: "research",
      title: `Filecoin / DePIN News Digest — ${date}`,
      description:
        "Daily curated news digest for Filecoin, decentralised storage, and DePIN, " +
        "produced by the RFS-4 agent economy testbed.",
    },
  };
}
